name: Keep Repository Active

on:
  schedule:
    - cron: "0 0 * * 0" # Runs at 00:00 UTC every Sunday
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write

jobs:
  update-timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update timestamp
        run: |
          echo "Last activity: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" > last_activity.txt

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add last_activity.txt
          git commit -m "Update last activity timestamp [skip ci]"
          git push
