name: Release Bit Bare Server Nightly Image and Tag
on:
  schedule:
    - cron: '0 23 * * *' # Run daily at 11:00 PM UTC
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Install Bit and get version
        run: |
          npm install -g @teambit/bvm
          SHELL=bash npx @teambit/bvm config set RELEASE_TYPE nightly
          SHELL=bash npx @teambit/bvm install
          export PATH=$HOME/bin:$PATH
          BIT_VERSION=$(bit -v)
          echo "BIT_VERSION=$BIT_VERSION" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.server
          push: true
          tags: |
            bitsrc/server:nightly
            bitsrc/server:${{ env.BIT_VERSION }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            NIGHTLY=true
            NODE_VERSION=22-alpine
