name: Release Nightly Image
on:
  schedule:
    - cron: '0 22 * * *' # Run at 10:00 PM UTC (2 hours before midnight)
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            bitsrc/nightly:latest
          platforms: linux/amd64,linux/arm64
          build-args: |
            NIGHTLY=true
