name: Release Alpine Stable Image GH

on:
  schedule:
    - cron: '0 21 * * *' # Run at 10:00 PM UTC (2 hours before midnight)
  workflow_dispatch:

# Set permissions globally for all jobs in the workflow
permissions:
  contents: read
  packages: write
  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # GitHub username
          password: ${{ secrets.GITHUB_TOKEN }} # GitHub's default token

      # Install Bit and get version
      - name: Install Bit and get version
        run: |
          npm install -g @teambit/bvm
          SHELL=bash npx @teambit/bvm install
          export PATH=$HOME/bin:$PATH
          BIT_VERSION=$(bit -v)
          echo "BIT_VERSION=$BIT_VERSION" >> $GITHUB_ENV

      # Build and push Docker image to GitHub Container Registry
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.alpine
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/stable:latest-alpine
            ghcr.io/${{ github.repository_owner }}/stable:${{ env.BIT_VERSION }}-alpine
          platforms: linux/amd64,linux/arm64
