name: Release Docker Image
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      bit_version:
        description: 'BIT_VERSION'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get Git tag name
        id: get_tag_name
        run: echo "::set-output name=TAG_NAME::${{ github.event.inputs.bit_version || (git describe --tags --abbrev=0) }}"

      - name: Log in to Docker registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: bitsrc/dev:latest
          platforms: linux/amd64,linux/arm64
          build-args: |
            BIT_VERSION=${{ steps.get_tag_name.outputs.TAG_NAME }}

